use_frameworks!

target 'CoordinatorKit_Example' do
  pod 'CoordinatorKit', :path => '../'

  target 'CoordinatorKit_Tests' do
    inherit! :search_paths

    pod 'Quick'
  pod 'Nimble', '~> 5.0.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
